{"version":3,"file":"throwError.js","sourceRoot":"","sources":["../../src/throwError.ts"],"names":[],"mappings":";;AAAA;;;;;;;;;;;;;;;GAeG;AACH,IAAM,UAAU,GACd,UAAqB,OAAwB;IAC7C,OAAA,UAAC,KAAQ;QACP,MAAM,OAAO,CAAC,KAAK,CAAC,CAAC;IACvB,CAAC;AAFD,CAEC,CAAC;AAEJ,kBAAe,UAAU,CAAC","sourcesContent":["/**\n * throw result of `toError`\n *\n * @example\n * ```ts\n * const result: never = pipe(\n *   0,\n *\n *   throwError((input) => Error(`input is ${input}`)),\n *\n *   (input: never) => {\n *     // unreachable point\n *   },\n * );\n * ```\n */\nconst throwError =\n  <T, E extends Error>(toError: (input: T) => E) =>\n  (input: T) => {\n    throw toError(input);\n  };\n\nexport default throwError;\n"]}